<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LoactionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('locations')->insert([
            ["name_ar" => "ABILENE ", "name_en" => "ABILENE "],
            ["name_ar" => "ADESA Los Angeles ", "name_en" => "ADESA Los Angeles "],
            ["name_ar" => "ADESA San Diego ", "name_en" => "ADESA San Diego "],
            ["name_ar" => "AKRON - CANTON ", "name_en" => "AKRON - CANTON "],
            ["name_ar" => "ALBANY ", "name_en" => "ALBANY "],
            ["name_ar" => "ALBUQUERQUE ", "name_en" => "ALBUQUERQUE "],
            ["name_ar" => "ALTOONA (Ebensburg) ", "name_en" => "ALTOONA (Ebensburg) "],
            ["name_ar" => "AMARILLO ", "name_en" => "AMARILLO "],
            ["name_ar" => "ANAHEIM ", "name_en" => "ANAHEIM "],
            ["name_ar" => "ANDREWS ", "name_en" => "ANDREWS "],
            ["name_ar" => "ANTELOPE ", "name_en" => "ANTELOPE "],
            ["name_ar" => "APPLETON ", "name_en" => "APPLETON "],
            ["name_ar" => "ASHEVILLE (Fletcher) ", "name_en" => "ASHEVILLE (Fletcher) "],
            ["name_ar" => "ASHLAND ", "name_en" => "ASHLAND "],
            ["name_ar" => "ATLANTA EAST/WEST/NORTH/SOUTH ", "name_en" => "ATLANTA EAST/WEST/NORTH/SOUTH "],
            ["name_ar" => "AUSTIN (New Braunfels) ", "name_en" => "AUSTIN (New Braunfels) "],
            ["name_ar" => "AVENEL NEW JERSEY ", "name_en" => "AVENEL NEW JERSEY "],
            ["name_ar" => "BAKERSFIELD ", "name_en" => "BAKERSFIELD "],
            ["name_ar" => "BALTIMORE (Finksburg) ", "name_en" => "BALTIMORE (Finksburg) "],
            ["name_ar" => "BATON ROUGE (Greenwell Springs) ", "name_en" => "BATON ROUGE (Greenwell Springs) "],
            ["name_ar" => "BILLINGS ", "name_en" => "BILLINGS "],
            ["name_ar" => "BIRMINGHAM (Hueytown) ", "name_en" => "BIRMINGHAM (Hueytown) "],
            ["name_ar" => "BOISE ", "name_en" => "BOISE "],
            ["name_ar" => "BOSTON (Lancaster) ", "name_en" => "BOSTON (Lancaster) "],
            ["name_ar" => "BOWLING GREEN ", "name_en" => "BOWLING GREEN "],
            ["name_ar" => "BRIDGEPORT ", "name_en" => "BRIDGEPORT "],
            ["name_ar" => "BUCKHANNON ", "name_en" => "BUCKHANNON "],
            ["name_ar" => "BUFFALO ", "name_en" => "BUFFALO "],
            ["name_ar" => "BURLINGTON (Essex) ", "name_en" => "BURLINGTON (Essex) "],
            ["name_ar" => "CANDIA ", "name_en" => "CANDIA "],
            ["name_ar" => "Carson ACE ", "name_en" => "Carson ACE "],
            ["name_ar" => "CARTERSVILLE ", "name_en" => "CARTERSVILLE "],
            ["name_ar" => "Casper ", "name_en" => "Casper "],
            ["name_ar" => "CENTRAL NEW JERSEY (Morganville) ", "name_en" => "CENTRAL NEW JERSEY (Morganville) "],
            ["name_ar" => "CHAMBERSBURG ", "name_en" => "CHAMBERSBURG "],
            ["name_ar" => "CHARLESTON (Hurricane) ", "name_en" => "CHARLESTON (Hurricane) "],
            ["name_ar" => "CHARLESTON (Hurricane) ", "name_en" => "CHARLESTON (Hurricane) "],
            ["name_ar" => "CHARLOTTE ", "name_en" => "CHARLOTTE "],
            ["name_ar" => "CHATTANOOGA ", "name_en" => "CHATTANOOGA "],
            ["name_ar" => "CHICAGO NORTH /SOUTH/EAST/WEST ", "name_en" => "CHICAGO NORTH /SOUTH/EAST/WEST "],
            ["name_ar" => "CHINA GROVE ", "name_en" => "CHINA GROVE "],
            ["name_ar" => "CINCINNATI - SOUTH/WEST ", "name_en" => "CINCINNATI - SOUTH/WEST "],
            ["name_ar" => "CLEARWATER ", "name_en" => "CLEARWATER "],
            ["name_ar" => "CLEVELAND ", "name_en" => "CLEVELAND "],
            ["name_ar" => "Colorado Springs ", "name_en" => "Colorado Springs "],
            ["name_ar" => "COLTON ", "name_en" => "COLTON "],
            ["name_ar" => "COLUMBIA ", "name_en" => "COLUMBIA "],
            ["name_ar" => "COLUMBIA ", "name_en" => "COLUMBIA "],
            ["name_ar" => "COLUMBUS ", "name_en" => "COLUMBUS "],
            ["name_ar" => "CONCORD ", "name_en" => "CONCORD "],
            ["name_ar" => "CORPUS CHRISTI ", "name_en" => "CORPUS CHRISTI "],
            ["name_ar" => "CULPEPR ", "name_en" => "CULPEPR "],
            ["name_ar" => "DALLAS ", "name_en" => "DALLAS "],
            ["name_ar" => "DALLAS WORTH ", "name_en" => "DALLAS WORTH "],
            ["name_ar" => "DANVILLE (Chatham) ", "name_en" => "DANVILLE (Chatham) "],
            ["name_ar" => "DAVENPORT ", "name_en" => "DAVENPORT "],
            ["name_ar" => "DAYTON ", "name_en" => "DAYTON "],
            ["name_ar" => "DENVER ", "name_en" => "DENVER "],
            ["name_ar" => "DES MOINES ", "name_en" => "DES MOINES "],
            ["name_ar" => "DETROIT (Woodhaven) ", "name_en" => "DETROIT (Woodhaven) "],
            ["name_ar" => "DOTHAN ", "name_en" => "DOTHAN "],
            ["name_ar" => "DREAM RIDES ", "name_en" => "DREAM RIDES "],
            ["name_ar" => "DUNDALK ", "name_en" => "DUNDALK "],
            ["name_ar" => "EAST BAY ", "name_en" => "EAST BAY "],
            ["name_ar" => "EL PASO ", "name_en" => "EL PASO "],
            ["name_ar" => "ENGLISHTOWN ", "name_en" => "ENGLISHTOWN "],
            ["name_ar" => "ERIE (Garland) ", "name_en" => "ERIE (Garland) "],
            ["name_ar" => "EUGENE ", "name_en" => "EUGENE "],
            ["name_ar" => "EXETER ", "name_en" => "EXETER "],
            ["name_ar" => "FAIRBURN ", "name_en" => "FAIRBURN "],
            ["name_ar" => "FARGO (West Fargo) ", "name_en" => "FARGO (West Fargo) "],
            ["name_ar" => "FAYETTEVILLE (Prairie Grove) ", "name_en" => "FAYETTEVILLE (Prairie Grove) "],
            ["name_ar" => "FLINT ", "name_en" => "FLINT "],
            ["name_ar" => "FONTANA ", "name_en" => "FONTANA "],
            ["name_ar" => "FORT LAUDERDALE ", "name_en" => "FORT LAUDERDALE "],
            ["name_ar" => "FORT MYERS ", "name_en" => "FORT MYERS "],
            ["name_ar" => "FORT WAYNE ", "name_en" => "FORT WAYNE "],
            ["name_ar" => "FORTH WORTH (Haslet) ", "name_en" => "FORTH WORTH (Haslet) "],
            ["name_ar" => "Fredericksburg ", "name_en" => "Fredericksburg "],
            ["name_ar" => "FREETOWN ", "name_en" => "FREETOWN "],
            ["name_ar" => "FREMONT ", "name_en" => "FREMONT "],
            ["name_ar" => "FRESNO ", "name_en" => "FRESNO "],
            ["name_ar" => "FT. PIERCE ", "name_en" => "FT. PIERCE "],
            ["name_ar" => "GASTONIA ", "name_en" => "GASTONIA "],
            ["name_ar" => "GLASSBORO ", "name_en" => "GLASSBORO "],
            ["name_ar" => "GRAHAM ", "name_en" => "GRAHAM "],
            ["name_ar" => "GRAND RAPIDS ", "name_en" => "GRAND RAPIDS "],
            ["name_ar" => "GREENSBORO (Graham) ", "name_en" => "GREENSBORO (Graham) "],
            ["name_ar" => "GREENVILLE (Simpsonville) ", "name_en" => "GREENVILLE (Simpsonville) "],
            ["name_ar" => "GREER ", "name_en" => "GREER "],
            ["name_ar" => "GRENADA ", "name_en" => "GRENADA "],
            ["name_ar" => "GULF COAST (Moss Point) ", "name_en" => "GULF COAST (Moss Point) "],
            ["name_ar" => "HAMMOND ", "name_en" => "HAMMOND "],
            ["name_ar" => "HAMPTON ", "name_en" => "HAMPTON "],
            ["name_ar" => "HARRISBURG (Grantville) ", "name_en" => "HARRISBURG (Grantville) "],
            ["name_ar" => "HARTFORD (SOUTH/EAST) ", "name_en" => "HARTFORD (SOUTH/EAST) "],
            ["name_ar" => "HAYWARD ", "name_en" => "HAYWARD "],
            ["name_ar" => "HELENA ", "name_en" => "HELENA "],
            ["name_ar" => "HIGH DESERT ", "name_en" => "HIGH DESERT "],
            ["name_ar" => "HOUSTON ", "name_en" => "HOUSTON "],
            ["name_ar" => "HUNTSVILLE (Athens) ", "name_en" => "HUNTSVILLE (Athens) "],
            ["name_ar" => "INDIANAPOLIS ", "name_en" => "INDIANAPOLIS "],
            ["name_ar" => "IONIA ", "name_en" => "IONIA "],
            ["name_ar" => "JACKSON (Florence) ", "name_en" => "JACKSON (Florence) "],
            ["name_ar" => "JACKSONVILLE ", "name_en" => "JACKSONVILLE "],
            ["name_ar" => "KANSAS CITY ", "name_en" => "KANSAS CITY "],
            ["name_ar" => "KANSAS CITY ", "name_en" => "KANSAS CITY "],
            ["name_ar" => "Kincheloe ", "name_en" => "Kincheloe "],
            ["name_ar" => "KNOXVILLE ", "name_en" => "KNOXVILLE "],
            ["name_ar" => "LAFAYETTE ", "name_en" => "LAFAYETTE "],
            ["name_ar" => "LANSING ", "name_en" => "LANSING "],
            ["name_ar" => "LAS VEGAS ", "name_en" => "LAS VEGAS "],
            ["name_ar" => "LAUREL ", "name_en" => "LAUREL "],
            ["name_ar" => "LEXINGTON ", "name_en" => "LEXINGTON "],
            ["name_ar" => "LEXINGTON ", "name_en" => "LEXINGTON "],
            ["name_ar" => "LINCOLN ", "name_en" => "LINCOLN "],
            ["name_ar" => "LINCOLN (Greenwood) ", "name_en" => "LINCOLN (Greenwood) "],
            ["name_ar" => "LITTLE ROCK (Conway) ", "name_en" => "LITTLE ROCK (Conway) "],
            ["name_ar" => "LITTLETON ", "name_en" => "LITTLETON "],
            ["name_ar" => "LIVINGSTON ", "name_en" => "LIVINGSTON "],
            ["name_ar" => "LONCOLN ", "name_en" => "LONCOLN "],
            ["name_ar" => "LONG BEACH ", "name_en" => "LONG BEACH "],
            ["name_ar" => "LONG ISLAND (Brookhaven) ", "name_en" => "LONG ISLAND (Brookhaven) "],
            ["name_ar" => "LONGVIEW ", "name_en" => "LONGVIEW "],
            ["name_ar" => "LOS ANGELES ", "name_en" => "LOS ANGELES "],
            ["name_ar" => "LOUISVILLE ", "name_en" => "LOUISVILLE "],
            ["name_ar" => "LOUISVILLE ", "name_en" => "LOUISVILLE "],
            ["name_ar" => "LUBBOCK ", "name_en" => "LUBBOCK "],
            ["name_ar" => "LUFKIN ", "name_en" => "LUFKIN "],
            ["name_ar" => "LUMBERTON ", "name_en" => "LUMBERTON "],
            ["name_ar" => "LYMAN ", "name_en" => "LYMAN "],
            ["name_ar" => "MACON ", "name_en" => "MACON "],
            ["name_ar" => "MADISON ", "name_en" => "MADISON "],
            ["name_ar" => "MANCHESTER (Salem) ", "name_en" => "MANCHESTER (Salem) "],
            ["name_ar" => "MARTINEZ ", "name_en" => "MARTINEZ "],
            ["name_ar" => "MCALLEN (Mercedes) ", "name_en" => "MCALLEN (Mercedes) "],
            ["name_ar" => "MEBANE ", "name_en" => "MEBANE "],
            ["name_ar" => "MEMPHIS ", "name_en" => "MEMPHIS "],
            ["name_ar" => "METRO DC (Brandywine) ", "name_en" => "METRO DC (Brandywine) "],
            ["name_ar" => "MIAMI CENTRAL/NORtH ", "name_en" => "MIAMI CENTRAL/NORtH "],
            ["name_ar" => "MILWAUKEE ", "name_en" => "MILWAUKEE "],
            ["name_ar" => "MINNEAPOLIS ", "name_en" => "MINNEAPOLIS "],
            ["name_ar" => "MISSOULA ", "name_en" => "MISSOULA "],
            ["name_ar" => "MOBILE (Eight Mile) ", "name_en" => "MOBILE (Eight Mile) "],
            ["name_ar" => "MOCKSVILLE ", "name_en" => "MOCKSVILLE "],
            ["name_ar" => "MONTGOMERY ", "name_en" => "MONTGOMERY "],
            ["name_ar" => "NASHVILLE (Lebanon) ", "name_en" => "NASHVILLE (Lebanon) "],
            ["name_ar" => "NEVADA ", "name_en" => "NEVADA "],
            ["name_ar" => "NEW CASTLE ", "name_en" => "NEW CASTLE "],
            ["name_ar" => "NEW ORLEANS ", "name_en" => "NEW ORLEANS "],
            ["name_ar" => "NEWBURGH (Marlboro) ", "name_en" => "NEWBURGH (Marlboro) "],
            ["name_ar" => "NORTH BOSTON (North Bellerica) ", "name_en" => "NORTH BOSTON (North Bellerica) "],
            ["name_ar" => "NORTH CHARLESTON ", "name_en" => "NORTH CHARLESTON "],
            ["name_ar" => "NORTH HOLLYWOOD ", "name_en" => "NORTH HOLLYWOOD "],
            ["name_ar" => "NORTHERN NEW JERSEY ", "name_en" => "NORTHERN NEW JERSEY "],
            ["name_ar" => "NORTHERN VIRGINIA ", "name_en" => "NORTHERN VIRGINIA "],
            ["name_ar" => "OCALA ", "name_en" => "OCALA "],
            ["name_ar" => "OGDEN ", "name_en" => "OGDEN "],
            ["name_ar" => "OKLAHOMA CITY ", "name_en" => "OKLAHOMA CITY "],
            ["name_ar" => "OMAHA ", "name_en" => "OMAHA "],
            ["name_ar" => "ORLANDO/NORTH ", "name_en" => "ORLANDO/NORTH "],
            ["name_ar" => "PADUCAH ", "name_en" => "PADUCAH "],
            ["name_ar" => "PASCO ", "name_en" => "PASCO "],
            ["name_ar" => "PENSACOLA (Milton) ", "name_en" => "PENSACOLA (Milton) "],
            ["name_ar" => "PEORIA (Pekin) ", "name_en" => "PEORIA (Pekin) "],
            ["name_ar" => "PERMIAN BASIN ", "name_en" => "PERMIAN BASIN "],
            ["name_ar" => "Perris ACE ", "name_en" => "Perris ACE "],
            ["name_ar" => "PHILADELPHIA (Pennsburg) ", "name_en" => "PHILADELPHIA (Pennsburg) "],
            ["name_ar" => "PHOENIX ", "name_en" => "PHOENIX "],
            ["name_ar" => "PITTSBURG NORTH/SOUTH ", "name_en" => "PITTSBURG NORTH/SOUTH "],
            ["name_ar" => "PORTAGE ", "name_en" => "PORTAGE "],
            ["name_ar" => "PORTLAND ", "name_en" => "PORTLAND "],
            ["name_ar" => "PORTLAND - SACO (Saco) ", "name_en" => "PORTLAND - SACO (Saco) "],
            ["name_ar" => "PORTLAND-GORHAM ", "name_en" => "PORTLAND-GORHAM "],
            ["name_ar" => "Providence ", "name_en" => "Providence "],
            ["name_ar" => "PULASKI ", "name_en" => "PULASKI "],
            ["name_ar" => "PUNTA GORDA ", "name_en" => "PUNTA GORDA "],
            ["name_ar" => "RALEIGH (Dunn) ", "name_en" => "RALEIGH (Dunn) "],
            ["name_ar" => "RANCHO CUCAMONGA ", "name_en" => "RANCHO CUCAMONGA "],
            ["name_ar" => "REDDING ", "name_en" => "REDDING "],
            ["name_ar" => "RENO ", "name_en" => "RENO "],
            ["name_ar" => "RICHMOND ", "name_en" => "RICHMOND "],
            ["name_ar" => "RIVERSIDE ", "name_en" => "RIVERSIDE "],
            ["name_ar" => "ROAMOKE ", "name_en" => "ROAMOKE "],
            ["name_ar" => "ROANOKE ", "name_en" => "ROANOKE "],
            ["name_ar" => "ROCHESTER (Leroy) ", "name_en" => "ROCHESTER (Leroy) "],
            ["name_ar" => "ROSEDALE ", "name_en" => "ROSEDALE "],
            ["name_ar" => "SACRAMENTO ", "name_en" => "SACRAMENTO "],
            ["name_ar" => "SALISBURY ", "name_en" => "SALISBURY "],
            ["name_ar" => "SALT LAKE CITY ", "name_en" => "SALT LAKE CITY "],
            ["name_ar" => "SAN ANTONIO ", "name_en" => "SAN ANTONIO "],
            ["name_ar" => "SAN BERNARDINO ", "name_en" => "SAN BERNARDINO "],
            ["name_ar" => "SAN DIEGO ", "name_en" => "SAN DIEGO "],
            ["name_ar" => "SAN FRANCISCO BAY ", "name_en" => "SAN FRANCISCO BAY "],
            ["name_ar" => "SAN JOSE ", "name_en" => "SAN JOSE "],
            ["name_ar" => "SAVANNAH ", "name_en" => "SAVANNAH "],
            ["name_ar" => "SCRANTON (Pittston) ", "name_en" => "SCRANTON (Pittston) "],
            ["name_ar" => "SEAFORD ", "name_en" => "SEAFORD "],
            ["name_ar" => "SEATTLE ", "name_en" => "SEATTLE "],
            ["name_ar" => "Shady Spring ", "name_en" => "Shady Spring "],
            ["name_ar" => "SHREVEPORT ", "name_en" => "SHREVEPORT "],
            ["name_ar" => "SIKESTON ", "name_en" => "SIKESTON "],
            ["name_ar" => "SIOUX FALLS ", "name_en" => "SIOUX FALLS "],
            ["name_ar" => "SOMERVILLE (Hillsborough) ", "name_en" => "SOMERVILLE (Hillsborough) "],
            ["name_ar" => "SOUTH BEND ", "name_en" => "SOUTH BEND "],
            ["name_ar" => "SOUTH BOSTON (Mendon) ", "name_en" => "SOUTH BOSTON (Mendon) "],
            ["name_ar" => "SOUTHERN CALIFORNIA ", "name_en" => "SOUTHERN CALIFORNIA "],
            ["name_ar" => "SOUTHERN ILLINOIS ", "name_en" => "SOUTHERN ILLINOIS "],
            ["name_ar" => "SOUTHERN NEW JERSEY (Turnersville) ", "name_en" => "SOUTHERN NEW JERSEY (Turnersville) "],
            ["name_ar" => "SPARTANBURG ", "name_en" => "SPARTANBURG "],
            ["name_ar" => "SPECIALTY DIVISION (WHEELING) ", "name_en" => "SPECIALTY DIVISION (WHEELING) "],
            ["name_ar" => "SPOKANE ", "name_en" => "SPOKANE "],
            ["name_ar" => "SPRINGFIELD ", "name_en" => "SPRINGFIELD "],
            ["name_ar" => "ST. CLOUD (Avon) ", "name_en" => "ST. CLOUD (Avon) "],
            ["name_ar" => "ST. LOUIS (Bridgeton) ", "name_en" => "ST. LOUIS (Bridgeton) "],
            ["name_ar" => "SUFFOLK ", "name_en" => "SUFFOLK "],
            ["name_ar" => "SUN VALLEY ", "name_en" => "SUN VALLEY "],
            ["name_ar" => "SYRACUSE (Central Square) ", "name_en" => "SYRACUSE (Central Square) "],
            ["name_ar" => "TALLAHASSEE (Midway) ", "name_en" => "TALLAHASSEE (Midway) "],
            ["name_ar" => "TAMPA ", "name_en" => "TAMPA "],
            ["name_ar" => "TANNER ", "name_en" => "TANNER "],
            ["name_ar" => "TAUNTON (EAST TAUNTON) ", "name_en" => "TAUNTON (EAST TAUNTON) "],
            ["name_ar" => "TEMPLETON ", "name_en" => "TEMPLETON "],
            ["name_ar" => "Texas Hobby ", "name_en" => "Texas Hobby "],
            ["name_ar" => "TIDEWATER (Yorktown) ", "name_en" => "TIDEWATER (Yorktown) "],
            ["name_ar" => "TIFTON ", "name_en" => "TIFTON "],
            ["name_ar" => "TORK SPRINGS ", "name_en" => "TORK SPRINGS "],
            ["name_ar" => "TRENTON ", "name_en" => "TRENTON "],
            ["name_ar" => "TUCSON ", "name_en" => "TUCSON "],
            ["name_ar" => "TULSA ", "name_en" => "TULSA "],
            ["name_ar" => "UTAH ", "name_en" => "UTAH "],
            ["name_ar" => "VALLEJO ", "name_en" => "VALLEJO "],
            ["name_ar" => "VAN NUYS ", "name_en" => "VAN NUYS "],
            ["name_ar" => "Waco ", "name_en" => "Waco "],
            ["name_ar" => "WALTON ", "name_en" => "WALTON "],
            ["name_ar" => "WASHINGTON DC (Waldorf ", "name_en" => "WASHINGTON DC (Waldorf "],
            ["name_ar" => "MD)", "name_en" => "MD)"],
            ["name_ar" => "WEST PALM BEACH ", "name_en" => "WEST PALM BEACH "],
            ["name_ar" => "FL ", "name_en" => "FL "],
            ["name_ar" => "WEST WARREN ", "name_en" => "WEST WARREN "],
            ["name_ar" => "WESTERN COLORADO ", "name_en" => "WESTERN COLORADO "],
            ["name_ar" => "WHEELING ", "name_en" => "WHEELING "],
            ["name_ar" => "WICHITA ", "name_en" => "WICHITA "],
            ["name_ar" => "WILMINGTON ", "name_en" => "WILMINGTON "],
            ["name_ar" => "WINDSOR ", "name_en" => "WINDSOR "],
            ["name_ar" => "WOODBURN ", "name_en" => "WOODBURN "],
            ["name_ar" => "YORK HAVEN ", "name_en" => "YORK HAVEN "],
            ["name_ar" => "York Springs ", "name_en" => "York Springs "],
            ["name_ar" => "LITTLETON ", "name_en" => "LITTLETON "],
            ["name_ar" => "WESTERN COLORADO ", "name_en" => "WESTERN COLORADO "],
            ["name_ar" => "Colorado Springs ", "name_en" => "Colorado Springs "],
            ["name_ar" => "DENVER ", "name_en" => "DENVER "],
        ]);
    }
}
