@extends('website.layout.main')
@section('title', __('content.home'))
@section('content')
    @include('website.partials.carousel')
    @include('website.partials.about')
    @include('website.partials.fact')
    @include('website.partials.service')
    @include('website.partials.feature')
    @include('website.partials.contact')
@endsection
